### ISSUE TITLE
SSL TrustStore per connection regression from 2.0 to 2.0.1

### ISSUE THREAD

**Issue by nhojpatrick** [jax-rs/api#562]
Via ClientBuilder.sslContext() I setup keystore and truststore configuration.

Testing using 2.0, per connection/request can have different keystore's and truststore's.

Testing using 2.0.1 the truststore is ignored and it picks up the jdk truststore. So I have to define vm parameters -Djavax.net.ssl.trustStore=X and -Djavax.net.ssl.trustStorePassword=Y. But this breaks per connection/request truststore's.

Due to security requirements, I'm not allowed to touch the default jdk/jre installation. So need to set configuration per request connection.

**Comment by pavelbucek** [comment]
Is this a spec issue or implementation issue? How are you testing this? Can you provide a reproducer?

// in any way, we are not able to fix this in 2.1, this came way too late do change anything :(

**Comment by nhojpatrick** [comment]
I'm using jersey to create a rest client, only just upgrading to the latest version of jersey, so only just picking up 2.0.1 instead of 2.0.

Setup a https server using a custom ca that require client certificates. Put your custom root ca into your truststore.jks and your client cert into your keystore.jks.
Then create a java client to call the server, using the Client Builder specify a ssl context. The ssl context points to your keystore and truststore.

I'll try and create a test setup, I'll also retry with the latest release 2.1 milestones and see if it contains the same issue.

**Comment by pavelbucek** [comment]
that implies issue with Jersey or somewhere else than in JAX-RS portion of the implementation.

I'm sorry, but it seems like the issue can't be moved - can you please file it again against https://github.com/jersey/jersey/issues (ideally with a reproducer).

Thanks!

**Comment by nhojpatrick** [comment]
I was actually working on this earlier today and tracked it down to jax-rs classes causing me the problem, so not a jersey issue.

I create a default Client with the correct configuration and sslContext, then 'clone' this using a line similar to below per request.
`ClientBuilder.newClient(default.getConfiguration());`

In my view I've set sslContext on the Client and that is part of the configuration, but getConfiguration and newClient don't transfer the sslContext into the new instance.

My question to developers is, how should I clone a default/template issue to be handed to individual requests. As I understand that Client is not thread safe so I need a new instance per request.
