### ISSUE TITLE
JAX-RS Launcher for Java SE

### ISSUE THREAD

**Issue by mkarg** [jax-rs/api#570]
The EG shall discuss whether it makes sense to have one standard Java SE launcher like "javax.ws.rs.server.Container.launch();" (for auto-detect use case / optionally with application class parameter to disable auto-detect). This might be useful to wrap the lots of existing proprietary solutions provided by current (microservice) frameworks.

**Comment by pavelbucek** [comment]
Duplicate of https://github.com/jax-rs/api/issues/509
