### ISSUE TITLE
2.1 maven integration issue

### ISSUE THREAD

**Issue by crizo23** [jax-rs/api#571]
I'm not sure if this is the right place to post this, but here goes.
I'm attempting to pull in jax-rs 2.1 in Gradle. Gradle complains that it can't resolve due to:
Could not HEAD 'http://central.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.$%7Bpackaging.type%7D'

As you can see, the packaging .type variable is not getting resolved. I'm wondering if it's because the maven profile isn't getting set due to an incorrect <jdk> value.

The [jax-rs 2.1 POM][1] defines the "jdk8-"  profile as: 
    <profile>
      <id>jdk8-</id>
      <activation>
        <jdk>(,9)</jdk>
      </activation>
    .. 
    </profile>

I'm wondering if the (,9) is preventing any profile from getting picked up:
    <jdk>(,9)</jdk>

According to the maven [range spec][2], should it be: 
    <jdk>(,1.9)</jdk>

**Comment by ChristianCiach** [comment]
2.1 is a dependency for Jersey Core Server » 2.26, so we cannot use Jersey Server at the moment. Even the download button

**Comment by pavelbucek** [comment]
This seems like a gradle issue.

(we don't see that in maven and we are referencing jax-rs api in multiple places; I don't believe this is related to any profile declared in pom.xml).

**Comment by ChristianCiach** [comment]
I am not convinced that it is a gradle issue.

I can't find anything about a magic variable called `${packaging.type}` and there is no `<properties>`-block inside the pom file to declare any custom defined properties..

**Comment by ChristianCiach** [comment]
I am sorry, I am wrong. There is a custom properties-block to declare this variable. I will ask the gradle guys for support.

**Comment by ChristianCiach** [comment]
Gradle has very limited support for pom-profiles, which are discouraged to use anyway - so much so, that even mvnrepository.com can't generate a download link.

It would be nice if you at least could define a profile that is active by default:

`<profile><activation><activeByDefault>true</activeByDefault></activation></profile>`

Such a profile is picked up by gradle. You can still override these properties depending on the JDK-versions. Gradle will ignore these additional profiles.

It this something you could do for us gradle users, please?

**Comment by pavelbucek** [comment]
As stated in the email communication, we can't just do that. Released artifacts are immutable.

And since this is not a bug in JAX-RS deployment descriptor - the issue is in how gradle parses/uses pom files - I don't see this as a reason for 2.1.1 release.

**Comment by crizo23** [comment]
So where does ownership lie for a pom.xml that doesn't play nice? Currently, Jersey and Swagger are negatively affected by this. Am I incorrect that these projects are the "customers" of jax-rs? Isn't jax-rs concerned with maximum adoption rate by making integration as easy as possible?

**Comment by ibaca** [comment]
Uhm, using a maven property in the type seems pretty bad idea. Anyway, I just created a gradle project and added `compile group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: '2.1'` and it works correctly so you should have some other problem.

**Comment by ChristianCiach** [comment]
> I just created a gradle project and added compile group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: '2.1' and it works correctly

It does not work for me. What repository and gradle version are you using?

**Comment by ibaca** [comment]
Version `gradle-3.5-rc-2` and `mavenCentral()` (I just created a new gradle project on intellij).

**Comment by sslavic** [comment]
This broke sbt builds too, probably because sbt uses Apache Ivy just like Gradle.

As workaround applied https://github.com/ronmamo/reflections/issues/169#issuecomment-288341587
```
initialize ~= { _ =>
  // this is a workaround for https://github.com/jax-rs/api/issues/571
  sys.props += "packaging.type" -> "jar"
}
```

**Comment by maltem-za** [comment]
See my linked issue #572 for an Ivy fix
