### ISSUE TITLE
Default value for @PathParam

### ISSUE THREAD

**Issue by ggam** [jax-rs/api#579]
`@PathParam` annotation requires the name of tha param to be specified. This attribute could be made optional and default to the name of the annotated element.

So instead of

```
@Path("hello")
public class HelloResource {

    @GET
    @Path("{name}/{surname}")
    public String hello(@PathParam("name") String name, @PathParam("surname") String surname) {
        return "Hello, " + name + " " + surname;
    }
}
```

We could just do:
```
@Path("hello")
public class HelloResource {

    @GET
    @Path("{name}/{surname}")
    public String hello(@PathParam String name, @PathParam String surname) {
        return "Hello, " + name + " " + surname;
    }
}
```

Method parameters in particular might be more problematic since they are not always available at runtime, but setter or field injection would easily work.

**Comment by pavelbucek** [comment]
I believe might be already tracked here.

The reason why this wasn't added is that the method parameter name is almost never available from the runtime and having the "default" not working in the most common usecase is not acceptable.

See https://github.com/jax-rs/api/issues/39 and https://github.com/jax-rs/api/issues/76.

(closing this one as a duplicate).

**Comment by FroMage** [comment]
I'm not sure it's not acceptable. As a user, I'd much rather get a mis-configuration exception at run-time if I've forgotten to add the required compiler flag, than repeat the parameter name everywhere, for absolutely no value and huge frustration.

After all, the choice is between one compiler flag, and very many path/query/matrix/etc… parameters that are not DRY and are the very definition of boilerplate. 

I understand at the time of writing JAX-RS parameter names were dropped by reflection, so there was a good reason at the time to require this duplicate information. I also understand the decision of javac to default to not store parameter names is as crazy as arbitrary, but I don't think users have to be punished for past limitations and bad default choices.

JAX-RS already throws run-time exceptions for mis-configured resources. This would just be one of them. With a clear error message it's trivial to fix by adding the right javac parameter. Much easier to fix than to edit the source code to duplicate every parameter name for no valid reason.

**Comment by ggam** [comment]
@FroMage I think is also important to remark that those annotations can also be used on class fields and I think setters, where it will always work. Also, any runtime exception could actually be a deployment time error, so the inconvenience would be minimum.
