### ISSUE TITLE
Add getUriInfo() to ClientRequestContext

### ISSUE THREAD

**Issue by aaronanderson** [jax-rs/api#580]
Currently there is no way to obtain the provided query parameters in a ClientRequestFilter implementation other than to split the query string from the URI which is inefficient. The server side ContainerRequestContext interface has access to the UriInfo which contains the getQueryParameters()  method which returns a useful  MultivaluedMap of the parameters.

The motivation behind this request is that I am trying to build a JAX-RS ClientRequestFilter that signs the request using the AWS  Signature Version 4 algorithm where parameter names and their sorted order are required.

**Comment by andymc12** [comment]
@aaronanderson Would it work to have a `UriInfo` field in your filter?  IIUC, you should be able to do something like this:

```
public class MyClientRequestFilter implements ClientRequestFilter {
    
    @Context
    UriInfo uriInfo;
    

    @Override
    public void filter(ClientRequestContext context) throws IOException {
        MultivaluedMap<String,String> queryParams = uriInfo.getQueryParameters();
        ...
```
Hope this helps

**Comment by aaronanderson** [comment]
Thank you very much, it works as documented. I was unaware that an UriInfo instance could be injected in a client filter like it can be with a server side filter. Thanks!!!!
